"Changes: Sprites":
- '**/*.rsi/*.png'

"Changes: Map":
- 'Resources/Maps/*.yml'
- 'Resources/Prototypes/Maps/*.yml'

"Changes: UI":
- '**/*.xaml*'

"No C#":
- all: ["!**/*.cs"]

"April Fools (merge for one day)":
- base-branch: 'april-fools-2024'
